matrix-org/rageshake

hooks/pre-commit

* Run the checks against the git index (ie, what you're about to commit), rather than the working copy
* Add the changes made by `go fmt` back to the index, so that they are included in the commit, as well as the working copy.

fix up the pre-commit hook

---

README.md
src/github.com/matrix-org/rageshake/logserver.go
src/github.com/matrix-org/rageshake/main.go

If the client accepts gzip, just serve the file as a gzip-encoded plain text.
If it doesn't, gunzip it first.

Serve log files as plain text

---

src/github.com/matrix-org/rageshake/submit.go
src/github.com/matrix-org/rageshake/submit_test.go

current riot-android stuffs everything into the 'version' field; I don't really
want that ending up in the github issue (especially the mxid), and I don't want
to have to wait for an update to riot-android to land, so let's unpick
it into 'data'.

Undo the android client's mangled submissions

---

README.md
src/github.com/matrix-org/rageshake/logserver.go
src/github.com/matrix-org/rageshake/submit.go
src/github.com/matrix-org/rageshake/submit_test.go

If a 'file' parameter is provided, save it as a file on disk. Also include a link to it from the github issue.

Add support for attaching files to reports

---

README.md
src/github.com/matrix-org/rageshake/submit.go
src/github.com/matrix-org/rageshake/submit_test.go

the mobile guys want to be able to distinguish between crash.log and other logs.
Builds on https://github.com/matrix-org/rageshake/pull/17.

If a log is uploaded with a sensible filename, preserve it

---

src/github.com/matrix-org/rageshake/submit.go
src/github.com/matrix-org/rageshake/submit_test.go

Make sure we read the appname from JSON rageshakes, so that issues are correctly filed into github.
(This was affecting riot-web 0.9.9 and earlier; later versions are using the multipart interface; riot-android was special-cased anyway; riot-ios has never used the JSON interface.)
(And this, children, is why we write tests.)

Unbreak github submits for json rageshakes

---

.travis.yml
README.md

golint no longer supports 1.7. (https://github.com/golang/go/issues/28291).
It's time to update.

Update go version

---

changelog.d/39.bugfix
main.go
submit.go

Fixes a bug I ran into while testing matrix-org/matrix-react-sdk#7307, which causes receiving and sending clients to submit rageshakes near-simultaneously. If the timestamps collide, only one client's rageshake succeeds, and the other one fails with a 500.

Add random string to report directories to prevent time-based collisions

---

README.md
changelog.d/42.misc
go.mod

The linting scripts don't run on 1.15 any more, so builds are not
running against 1.15 any more.
Technically it will still compile and run against go 1.15 but if we
can't verify it in CI, it's not known to be true in future.

Update go version to 1.16

---

.github/workflows/docker.yaml
Dockerfile
changelog.d/47.misc
docker-bake.hcl

This does two things:
- enhance the Dockerfile to be multi-arch capable (also allows it to run as non-root)
- build and push a Docker image on ghcr.io/matrix-org/rageshake via GitHub Actions
There are a few important things to note about the changes in the Dockerfile:
- the runtime image is based on an image [from the distroless project](https://github.com/GoogleContainerTools/distroless)
- this allows for the container to run as non-root (there is a `/etc/passwd` entry for that)
- the image can be cross-compiled (e.g. building the amd64 image from an arm64 host and vice-versa) with no qemu emulation involved. This however requires a buildkit-enabled Docker (which is the default on Docker Desktop), e.g. `export DOCKER_BUILDKIT=1` on Linux
- I tested the image both on my M1 MacBook (arm64) …

Build and push multi-arch Docker images on ghcr.io

---

Makefile
README.md
changelog.d/50.feature
docs/generic_webhook.md
main.go
rageshake.sample.yaml
submit.go

Background submission to a notification server that doesn't block rageshake submission.
Timeout requests after 300s (to provide some wiggle room for servers that choose to take action inline)
Add docs on the format of the endpoint (though much of it is pass-through so there is no fixed schema in most cases)

Initial attempt at a generic webhook for reports.

---

changelog.d/52.feature
logserver.go
submit.go

The limit was there to make arbitrary file download hard, json files are mostly treated the same as text files so this should be fine.

Allow upload of files with a .json postfix.

---

README.md
changelog.d/53.feature
logserver.go

This will make it easier to get all logs for a given bug; preventing users
needing to run scripts to download all files.
- we cannot make the link exist in the directory listing as there are scripts
that automate downloads which would pick this up.
- Unsure if "?format=tar.gz" is the right option to enable this; I couldn't think
of something easy to do but hard to not get picked up by existing automation, and
wouldn't conflict with existing filenames. Suggestions welcome.

Serve a tarball containing the contents of a given directory.

---

changelog.d/54.feature
logserver.go
main.go
submit.go
submit_test.go

Rageshakes are too numerous for just uploading to github any more.
The generic webhook (and other) mechanism are able to track a greater volume of requests than simply uploading to github; however this means that we are going to be unable to use the issue ID generated by the github upload to track the rageshake.
We do create a unique ID for the on-disk rageshake, we expose this prefix as an ID in the objects we send onwards via the generic webhook API, which can then be used in external systems to uniquely identify this rageshake.
Technically this isn't any information that isn't in the ListingURL already, but i feel having a separate parameter storing the unique ID (such that it can evolve separately from the listingURL) is the right way to go.

Persist prefix as a unique id in rageshakes

---

changelog.d/67.feature
docs/blocked_rageshake.md
main.go
rageshake.sample.yaml
scripts/lint.sh
submit.go
submit_test.go

Optionally admins can now set a list of application names that will be accepted by this server. 
This is in reaction to admins spending time triaging bug reports for applications they don't own / can't do anything with.
The behaviour will stay as before (all applications permitted)  if the option is unset or an empty list; but will log a new warning on startup to say this behaviour is occuring.
If the report is blocked, the error message will include a link to the docs/blocked_rageshake.md file which contains some pointers on why and what to do afterwards; This isn't strictly neccessary but should ease peoples' debugging flows from that point.

Block applications not listed in an allow list.

---

.github/workflows/build.yaml
RELEASING.md
changelog.d/70.misc

Updates the release process such that creation of a github Release will be enough to trigger the docker image build and the rageshake.tar.gz to be uploaded to the release.
Requires that we move to a full "semver" semantic version in order to trigger the various tools to work; so no more `v1.8` ; we should use  `v1.9.0`.
Fixes #69  
Fixes #51

Extra automation for release process (building binaries and docker containers)

---

.github/workflows/docker.yaml
Dockerfile
changelog.d/71.misc
docker-bake.hcl

The two changes are:
- do not tag both rageshake and the -debug flavour as `latest` - only the main build.
- Create a python:3-slim based container to host the scripts for usage.
Tested on this fork of the repo; we can see:
- the correct version is tagged `latest` here: https://github.com/michaelkaye/rageshake/pkgs/container/rageshake/versions?filters[version_type]=tagged 
- the new docker container holding the script is here: https://github.com/michaelkaye/rageshake/pkgs/container/rageshake/scripts/versions?filters[version_type]=tagged
- the new docker container contains the script and works at a basic level
```
michaelk@michaelk-XPS-13-9370:~$ docker run -it ghcr.io/michaelkaye/rageshake/scripts:latest python cleanup.py -h
usage: cleanup.py [-h] (--max-days MAX_DAYS | --days-to-check …
```

Refactor docker build

---

README.md
changelog.d/72.feature
scripts/cleanup.py

This is useful in the situation where you want to run this as a sidecar in a k8s pod, because while k8s has the concept of a CronJob - it doesn't run within the same pod; so you'd end up with two pods both needing to mount a block device (say, where you keep the bugs) read-write; which I don't believe works well. 
Have tested it with an invocation like this to test every 0.01 hours, which ran as expected
`michaelk@michaelk-XPS-13-9370:~/work/rageshake$ ./scripts/cleanup.py --repeat-delay-hours 0.01 --max-days 100 --path /home/michaelk/bugs/ --dry-run element-web:10` 
The following both run exactly once, which seems valid.
`michaelk@michaelk-XPS-13-9370:~/work/rageshake$ ./scripts/cleanup.py --repeat-delay-hours 0 --max-days 100 --path /home/michaelk/bugs/ --dry-run element-web:10` 
and …

Enhance scripts/cleanup.py to be able to run as a continual task.

---

changelog.d/81.feature
submit.go

This adds a link to the full archive of the rageshake logs, avoiding a few manual steps to download them. For what it's worth, the server will happily respond with the full archive even in the presence of a trailing slash in the `listingURL` (it might be an HTTP thing).

add link to archive in the submitted issue

---

CHANGES.md
README.md
main.go
rageshake.sample.yaml
submit.go
submit_test.go
templates/README.md
templates/email_body.tmpl
templates/issue_body.tmpl

The driver for this is that I want to add a link to our internal rageshake-search tool to the body of reported issues. Rather than add more magic special-casing that, making the format of issue bodies more configurable seems a good thing.

Generate emails and github/gitlab issue bodies from a template

---

changelog.d/86.feature
go.mod
go.sum
submit.go
submit_test.go

I've had to look up UA's far too many times

Parse user agent into a human-friendly string on submission

---

changelog.d/88.feature
docs/blocked_rageshake.md
main.go
main_test.go
rageshake.sample.yaml
submit.go

Sometimes users send something they really should not in their rageshake descriptions. I propose here an approach to reject rageshakes whose description matches a regex. The rejection reason is reflected client-side so the user's client can show them want went wrong.
The sample config file provides a regex to reject user texts that could contain a recovery key.
TODO if we like this approach:
- <del>Update `submit_test.go`</del>

Reject user texts matching a regex

---

changelog.d/95.bugfix
scripts/cleanup.py

The `details.log.gz` file contains user input, so may contain malformed UTF-8. We need to be resilient to such problems.

cleanup.py: guard against bad UTF in `details.log.gz`

---

docs/api.md

Coming to these docs without knowing the project, this sounded to me like "if rageshakes are disabled, the field will be omitted" as I was unaware until looking at [the code](https://github.com/matrix-org/rageshake/blob/af89ac135d489d182627c4d36971472a3078cc1c/submit.go#L107-L108) that you can run a rageshake server that doesn't then create GitHub/GitLab issues.

Clarify the omission of report_url in the response.
